nprompts = 600
presets = {"psy1": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False, "num_prompts": nprompts,
                         "neg_prompt_inject": "(((Creepy))), ((Frightening)), Open Mouth, (((Bad Trip)))", "add_captions": False,
                         "theme": "A voyage through a psychedelic alternate universe. The story should describe the strange but "
                                  "beautiful things and creatures you can encounter there.",
                         "prompt_inject": "Alex Grey 3D Render", "music_inject": ""},
           "psy2": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False, "num_prompts": nprompts,
                         "neg_prompt_inject": "(((Creepy))), ((Frightening)), Open Mouth, (((Bad Trip)))",
                         "add_captions": False,
                         "theme": "A DMT Trip in a bright colorful dreamland",
                         "prompt_inject": "Acid Psychedelic 3D Artistic Render", "music_inject": ""},
           "dino1": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False, "num_prompts": nprompts,
                         "neg_prompt_inject": "(((Creepy))), ((Frightening)), Open Mouth, (((Bad Trip)))",
                         "add_captions": False,
                         "theme": "A day in in the prehistoric dinosaur world.",
                         "prompt_inject": "3D Artistic Render", "music_inject": ""},
           "dino2": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False,
                         "neg_prompt_inject": "(((Creepy))), ((Frightening)), Open Mouth, (((Bad Trip)))",
                         "add_captions": False,
                         "theme": "The day of the extinction event of the prehistoric dinosaur world..",
                          "music_inject": ""},
           "techno1": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False, "num_prompts": nprompts,
                    "neg_prompt_inject": "(Creepy), Open Mouth, (((Bad Trip)))",
                    "add_captions": False,
                    "theme": "An alien rave",
                    "prompt_inject": "Dark Techno Industrial Style, Geometric shapes.", "music_inject": ""},
           "techno2": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False,
                       "num_prompts": nprompts,
                       "neg_prompt_inject": "(Creepy), Open Mouth, (((Bad Trip)))",
                       "add_captions": False,
                       "theme": "An underground techno rave",
                       "prompt_inject": "Dark Techno Style, Geometric shapes.", "music_inject": ""},
           "space1": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False,
                     "num_prompts": nprompts,
                     "neg_prompt_inject": "poorly drawn, deviantart, mess, low quality, blurry, doll, painted face",
                     "add_captions": False,
                     "theme": "A cosmic trip through galaxies, stars, planets, wormholes and universes.",
                     "prompt_inject": "3D Artistic Render Masterpiece", "music_inject": ""},
           "space2": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False,
                      "num_prompts": nprompts,
                      "neg_prompt_inject": "poorly drawn, deviantart, mess, low quality, blurry, doll, painted face(((Bad Trip)))",
                      "add_captions": False,
                      "theme": "A cosmic trip through galaxies, stars, planets, wormholes and universes.",
                      "prompt_inject": "Flashy psychedelic art masterpiece", "music_inject": ""},
           "meditation": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False,
                      "num_prompts": nprompts,
                      "neg_prompt_inject": "poorly drawn, deviantart, mess, low quality, blurry, doll, painted face(((Bad Trip)))",
                      "add_captions": False,
                      "theme": "The story of Gaining enlightenment",
                      "prompt_inject": "Sacred Geometry", "music_inject": ""},
           "mushrooms": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False,
                      "num_prompts": nprompts,
                      "neg_prompt_inject": "poorly drawn, deviantart, mess, low quality, blurry, (((Bad Trip))),((Ugly))",
                      "add_captions": False,
                      "theme": "A trip through the relam of mushroomland where all types and forms of trippy mushrooms exist",
                      "prompt_inject": "Flashy psychedelic art masterpiece", "music_inject": ""},
           "biomes": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False,
                      "num_prompts": nprompts,
                      "neg_prompt_inject": "(((Unrealistic))), ((Ugly)), Open Mouth, ((Deformed))",
                      "add_captions": False,
                      "theme": "Different planets with biomes like ice planet, fire planet etc. Use a wide variety of biomes in your story.",
                      "prompt_inject": "Hasselblad award-winning sharp photography", "music_inject": ""},
           "elves": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False,
                      "num_prompts": nprompts,
                      "neg_prompt_inject": "(((Unrealistic))), ((Ugly)), Open Mouth, ((Deformed))",
                      "add_captions": False,
                      "theme": "A documentary about the lives of the elves in their enchanted forest. The documentary shows the attractive elves in their dayly lives.",
                      "prompt_inject": "Leica portrait of", "music_inject": ""},
           "underwater": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False,
                     "num_prompts": nprompts,
                     "neg_prompt_inject": "(((Unrealistic))), ((Ugly)), Open Mouth, ((Deformed))",
                     "add_captions": False,
                     "theme": "A documentary about the wonders of the underwater world.",
                     "prompt_inject": "Leica portrait of", "music_inject": ""},
           "zengarden": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False,
                          "num_prompts": nprompts,
                          "neg_prompt_inject": "(((Unrealistic))), ((Ugly)), Open Mouth, ((Deformed))",
                          "add_captions": False,
                          "theme": "A relaxing story about japanese zen gardens.",
                          "prompt_inject": "Japanese art masterpiece", "music_inject": ""},
           }
