nprompts = 600
presets = {"psy1": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False, "num_prompts": nprompts,
                         "neg_prompt_inject": "(((Creepy))), ((Frightening)), Open Mouth, (((Bad Trip)))", "add_captions": False,
                         "theme": "A voyage through a psychedelic alternate universe. The story should describe the strange but "
                                  "beautiful things and creatures you can encounter there.",
                         "prompt_inject": "Alex Grey 3D Render", "music_inject": ""},
           "psy2": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False, "num_prompts": nprompts,
                         "neg_prompt_inject": "(((Creepy))), ((Frightening)), Open Mouth, (((Bad Trip)))",
                         "add_captions": False,
                         "theme": "A DMT Trip in a bright colorful dreamland",
                         "prompt_inject": "Acid Psychedelic 3D Artistic Render", "music_inject": ""},
           "dino1": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False, "num_prompts": nprompts,
                         "neg_prompt_inject": "(((Creepy))), ((Frightening)), Open Mouth, (((Bad Trip)))",
                         "add_captions": False,
                         "theme": "A day in in the prehistoric dinosaur world.",
                         "prompt_inject": "3D Artistic Render", "music_inject": ""},
           "dino2": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False,
                         "neg_prompt_inject": "(((Creepy))), ((Frightening)), Open Mouth, (((Bad Trip)))",
                         "add_captions": False,
                         "theme": "The day of the extinction event of the prehistoric dinosaur world..",
                          "music_inject": ""},
           "techno1": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False, "num_prompts": nprompts,
                    "neg_prompt_inject": "(Creepy), Open Mouth, (((Bad Trip)))",
                    "add_captions": False,
                    "theme": "An alien rave",
                    "prompt_inject": "Dark Techno Industrial Style, Geometric shapes.", "music_inject": ""},
           "techno2": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False,
                       "num_prompts": nprompts,
                       "neg_prompt_inject": "(Creepy), Open Mouth, (((Bad Trip)))",
                       "add_captions": False,
                       "theme": "An underground techno rave",
                       "prompt_inject": "Dark Techno Style, Geometric shapes.", "music_inject": ""},
           "space1": {"duration_single_trans": 6, "depth_strength": 0.55, "add_watermark": False,
                     "num_prompts": nprompts,
                     "neg_prompt_inject": "(((Creepy))), ((Frightening)), Open Mouth, (((Bad Trip)))",
                     "add_captions": False,
                     "theme": "A cosmic trip through galaxies, stars, planets, wormholes and universes.",
                     "prompt_inject": "3D Artistic Render Masterpiece", "music_inject": ""},
           }